// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/register_form_repository.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/kindaidensan/UMR/domain"
	reflect "reflect"
)

// MockRegisterFormRepository is a mock of RegisterFormRepository interface
type MockRegisterFormRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterFormRepositoryMockRecorder
}

// MockRegisterFormRepositoryMockRecorder is the mock recorder for MockRegisterFormRepository
type MockRegisterFormRepositoryMockRecorder struct {
	mock *MockRegisterFormRepository
}

// NewMockRegisterFormRepository creates a new mock instance
func NewMockRegisterFormRepository(ctrl *gomock.Controller) *MockRegisterFormRepository {
	mock := &MockRegisterFormRepository{ctrl: ctrl}
	mock.recorder = &MockRegisterFormRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRegisterFormRepository) EXPECT() *MockRegisterFormRepositoryMockRecorder {
	return m.recorder
}

// Set mocks base method
func (m *MockRegisterFormRepository) Set(arg0 domain.RegisterForm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockRegisterFormRepositoryMockRecorder) Set(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRegisterFormRepository)(nil).Set), arg0)
}

// Get mocks base method
func (m *MockRegisterFormRepository) Get() (domain.RegisterForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(domain.RegisterForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRegisterFormRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegisterFormRepository)(nil).Get))
}
